name: Go Lint, Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Lint
        uses: reviewdog/action-golangci-lint@53f8eabb87b40b1a2c63ec75b0d418bd0f4aa919 # v2.2.2

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [ lint ]
    steps:
      - name: Check out code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Install Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: '1.20'
        id: go

      - name: Build tool
        run: go build -v .

      - name: Test
        run: go test -v ./...
